// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_VALID   Status = 0
	Status_INVALID Status = 1
)

var Status_name = map[int32]string{
	0: "VALID",
	1: "INVALID",
}

var Status_value = map[string]int32{
	"VALID":   0,
	"INVALID": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type MessageRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MessageRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MessageRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type MessageResponse struct {
	Stats                Status   `protobuf:"varint,1,opt,name=stats,proto3,enum=v1.Status" json:"stats,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Api                  string   `protobuf:"bytes,5,opt,name=api,proto3" json:"api,omitempty"`
	VerifiedEmail        bool     `protobuf:"varint,6,opt,name=verifiedEmail,proto3" json:"verifiedEmail,omitempty"`
	Token                string   `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetStats() Status {
	if m != nil {
		return m.Stats
	}
	return Status_VALID
}

func (m *MessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MessageResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MessageResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MessageResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MessageResponse) GetVerifiedEmail() bool {
	if m != nil {
		return m.VerifiedEmail
	}
	return false
}

func (m *MessageResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("v1.Status", Status_name, Status_value)
	proto.RegisterType((*MessageRequest)(nil), "v1.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "v1.MessageResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xeb, 0xb6, 0x49, 0xda, 0x43, 0x94, 0xea, 0x40, 0xc8, 0x62, 0x8a, 0x22, 0x86, 0x8a,
	0x21, 0x52, 0x8b, 0x18, 0x19, 0x2a, 0xc1, 0x10, 0x09, 0x3a, 0x64, 0xe8, 0x6e, 0x94, 0x83, 0x5a,
	0xb4, 0x4d, 0xc8, 0xd9, 0xf9, 0x8f, 0xfc, 0x2b, 0x14, 0xbb, 0xa5, 0x44, 0x62, 0xf3, 0xfb, 0x7c,
	0xbe, 0x7b, 0xef, 0x0c, 0xa0, 0xac, 0xd9, 0xa4, 0x55, 0x5d, 0x9a, 0x12, 0xfb, 0xcd, 0x3c, 0x59,
	0xc1, 0xe4, 0x95, 0x98, 0xd5, 0x07, 0xe5, 0xf4, 0x65, 0x89, 0x0d, 0x5e, 0x41, 0x60, 0xca, 0x4f,
	0xda, 0x4b, 0x11, 0x8b, 0xd9, 0x38, 0xf7, 0x02, 0xa7, 0x30, 0x50, 0x95, 0x96, 0x7d, 0xc7, 0xda,
	0x63, 0x5b, 0x47, 0x3b, 0xa5, 0xb7, 0x72, 0xe0, 0xeb, 0x9c, 0x48, 0xbe, 0x05, 0x5c, 0xfc, 0x36,
	0xe4, 0xaa, 0xdc, 0x33, 0x61, 0x0c, 0x01, 0x1b, 0x65, 0xd8, 0x75, 0x9c, 0x2c, 0x20, 0x6d, 0xe6,
	0x69, 0x0b, 0x2c, 0xe7, 0xfe, 0x02, 0x25, 0x44, 0x3b, 0xff, 0xe8, 0x30, 0xe1, 0x28, 0xff, 0x9f,
	0x82, 0xd7, 0x10, 0x5a, 0xa6, 0x3a, 0x2b, 0xe4, 0xd0, 0xe1, 0x83, 0x3a, 0xba, 0x0c, 0x4e, 0x2e,
	0x6f, 0xe1, 0xbc, 0xa1, 0x5a, 0xbf, 0x6b, 0x2a, 0x9e, 0x5d, 0x9f, 0x30, 0x16, 0xb3, 0x51, 0xde,
	0x85, 0xa7, 0xcc, 0xd1, 0x9f, 0xcc, 0x77, 0x31, 0x84, 0xde, 0x26, 0x8e, 0x21, 0x58, 0x2f, 0x5f,
	0xb2, 0xa7, 0x69, 0x0f, 0xcf, 0x20, 0xca, 0x56, 0x5e, 0x88, 0xc5, 0x23, 0x0c, 0x97, 0xd6, 0x6c,
	0xf0, 0x01, 0x46, 0x6b, 0xb5, 0xd5, 0x85, 0x32, 0x84, 0xd8, 0xc6, 0xeb, 0xee, 0xf4, 0xe6, 0xb2,
	0xc3, 0xfc, 0x5a, 0x92, 0xde, 0x5b, 0xe8, 0xfe, 0xe1, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xa1,
	0x60, 0x3f, 0xad, 0x95, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Validate(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Validate(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/v1.Auth/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Validate(context.Context, *MessageRequest) (*MessageResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Validate(ctx context.Context, req *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Auth/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Validate(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _Auth_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
